### ISSUE TITLE
Unable to npm install

### ISSUE THREAD

**Issue by himerus** [phase2/particle#262]
After doing a checkout of latest `master`, running `npm install` resulted in the following issue:
### Summary
```
npm WARN stylelint-webpack-plugin@0.10.3 requires a peer of stylelint@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-webpack-plugin@0.10.3 requires a peer of webpack@^3 || ^2 || ^2.2.0-rc.0 || ^2.1.0-beta.0 || ^1.13.2 but none is installed. You must install peer dependencies yourself.
```
### Reproduction steps
`git clone git@github.com:phase2/particle.git`
`cd particle`
`npm install`

### Proposed fix
Installing styelint and weback (latest) both globally and in project had no effect on this error.

I've forked and tested the stylelint-webpack-plugin at https://github.com/himerus/stylelint-webpack-plugin/commit/76aa8757907f8468e0eb5ceb25899b2935f9a2b4

This update to the `peerDependencies ` in `package.json` seemed to fix the issue of me not being able to install.
I presume this should be posted upstream to https://github.com/waterfoul/stylelint-webpack-plugin, but wanted some verification I wasn't the only one that had seen this.

**Comment by tjheffner** [comment]
Thanks for the report, we are aware of these warnings. I'm curious, are they actually breaking your install? Are `npm run setup` and `npm run start` failing? I've been treating these warnings as noise so far because the stylelint-webpack-plugin is not yet updated for webpack 4 support. https://github.com/JaKXz/stylelint-webpack-plugin/pull/139 

The maintainer for stylelint-webpack-plugin has stated he's planning to rewrite the module to conform to webpack4 standards (https://github.com/JaKXz/stylelint-webpack-plugin/pull/140) but until that happens i've been taking the path of least resistance to get things running.

**Comment by himerus** [comment]
That's odd, I swear it didn't let me run `npm run setup` / `start` initially, but when I grab this in a clean checkout, yes, they are indeed JUST warnings.

**Comment by tjheffner** [comment]
In that case, I'm going to close this. It is noise but should be going away in the next few weeks, pending upstream updates to the stylelint-webpack-plugin. Thanks again for reporting :)
