### ISSUE TITLE
Drupal: why not use relative paths for library assets?

### ISSUE THREAD

**Issue by andriokha** [phase2/particle#460]
Hi,

I've noticed that the default Drupal theme library file [particle.libraries.yml](../blob/master/apps/drupal/particle.libraries.yml) contains absolute paths for JS and CSS. This seems to be an explicit change made in [1847512](https://github.com/phase2/particle/commit/18475121e82f2827d08db7dab1021ea10511d32c) as part of #259 which in turn references the CR [Libraries can now be overridden and extended by themes](https://www.drupal.org/node/2497313). Could someone confirm that there's a good reason not to have relative paths? Maybe something about referencing assets outside of the theme directory?

Thanks!

**Comment by illepic** [comment]
Hi @andriokha! About a year ago we were getting reports that Particle wasn't working on Pantheon and one of the **possible** culprits at the time was themes referencing assets outside the immediate theme.

We've since tracked down the issue to something unrelated, so I'm going to get a relative path back into the drupal libraries yaml file stat and test it out. Look for a PR soon.

**Comment by andriokha** [comment]
Ah great news, thanks!

**Comment by illepic** [comment]
@jengrace Can we hit this today for a 10.2.X release?

**Comment by illepic** [comment]
We just put in as relative to master: https://github.com/phase2/particle/pull/466

**Comment by illepic** [comment]
@hugonaili do you remember the reason we hard-coded these paths instead of relative pathing?

**Comment by hugonaili** [comment]
@illepic Yes it was due to the relative path issue on Pantheon, and putting absolute paths fixed it back then.
