### ISSUE TITLE
Namespaces from an app do not necessarily correlate to directories generated for that app

### ISSUE THREAD

**Issue by illepic** [phase2/particle#503]
See: https://www.drupal.org/project/components/issues/2993671#comment-12912396

Our design system provides a lot of namespaces. Drupal then comes around and references most of those namespaces ... but not necessarily all.

We need to ensure that the namespaces being written out to places like `particle.info.yml` lines up with what is actually used within those apps.

In the instance referenced in the Drupal issue above, the card-grid organisms was never referenced within the Drupal build, therefore it wasn't copied to the `dist/app-drupal/atomic/` directory. This caused the Component Libraries Drupal module to throw out the entire `@organisms` namespace.

**Comment by jryanconklin** [comment]
This issue was duplicated in issue 512. Closing that issue and copying text here:

## Problem / Motivation
The alpha version of the Component Library module no longer supports `component-libraries` that have unresolvable keys. A provided key that does not have a directory in `apps/dist` will cause a whitescreen. 

## Proposed Solution
We should provide a check in namespace maker to guarantee we only update keys with directories that are in `dist`.

**Comment by Nebel54** [comment]
I added a fix for this issue here: #525

**Comment by jryanconklin** [comment]
Resolved in #552
