### ISSUE TITLE
jQuery event listeners don't work in enable()?

### ISSUE THREAD

**Issue by xaqrox** [phase2/particle#522]
I am trying to register a listener on `drupalViewportOffsetChange` from within the `enable()` function of one of my components. I have `import $ from 'jquery'` at the top of the file, and can confirm that I can do things like change the background color of elements via jquery when I'm in the function. But when I inspect the `document`, there is no listener... Also I tried storing the jquery from the function in a global variable and then comparing it to `$` during some core code was executing in the debugger, and they are not the same object. I don't know if that's supposed to happen. Any insight would be greatly appreciated.

**Comment by xaqrox** [comment]
I should mention, I'm on version 10.0.0 I believe. Cloned the project last July.

**Comment by jryanconklin** [comment]
The project has changed quite a bit since July 2018. Can you confirm this is still an issue on the latest release? Also in which context are you trying to use `drupalViewportOffsetChange`? You wouldn't have access to this solely within Pattern Lab. Likely you'd have to merge in that code in Drupal's `index.js` rather than rely solely on the components enable:

https://github.com/phase2/particle/blob/master/apps/drupal/index.js

Closing this issue for now. But feel free to ping me and reopen if this is still an issue.
